### PR TITLE
Publication template fixes

### PR DESCRIPTION
**Pull request by Xiao-Chenguang**
This PR includes two fixes:

1. Remove useless style for publication images (the style config is wrong and does not work).
2. Rename the publication and service template from `.md` to `.html` (indicates itself as a template).

### CODE REVIEW

**Comment by Xiao-Chenguang** [comment]
we may need to modify the readme if the author agrees with the fixes above.

**Comment by yaoyao-liu** [comment]
Thank you for submitting this pull request, and I truly appreciate your effort in helping to clean up unnecessary code—this is very helpful! However, I would prefer not to convert the Markdown files into HTML files. For example, `services.md` is not intended to be a template HTML file; it is meant to be updated directly by users. My goal is to keep this repository as a simple template that users can easily edit using Markdown. Files like `publications.md` and `services.md` are provided as examples, and users are free to replace them with their own Markdown content.

Thank you again for your contributions and understanding!

**Comment by Xiao-Chenguang** [comment]
I understand your points. I am inspired by this repo and willing to improve it as feedback. Currently, the publication.md and services.md in the `_include` folder are in HTML format, and the correct extension helps to determine the toolchains when dealing with those files in my case. After that, to use the template, we are expected to edit the publication.md in the `_data` folder and the service.md in the `_include` folder. this is not a consistent practice and a bit confused. Maybe we can make the service.md a template only, and read the data from service.md from `_data` folder similar to the publication.

**Comment by yaoyao-liu** [comment]
Thanks again for your contributions! As I mentioned in my previous comment, I am happy to merge the solutions to any technical issues, e.g., cleaning up unnecessary code. However, for the code organization, I prefer to keep the current one. If you hope to improve the code organization, you may create an improved version based on this repository, and I am very happy to advertise it in the README of my repository.

**Comment by Xiao-Chenguang** [comment]
> you may create an improved version based on this repository, and I am very happy to advertise it in the README of my repository.

I am heapy to do that. The `md` extension is kept as original. The `services.md` is a template similar to `_include/publications.md` now. Customization of services can be done in the `_data/services.yml`.

**Comment by yaoyao-liu** [comment]
> > you may create an improved version based on this repository, and I am very happy to advertise it in the README of my repository.
> 
> I am heapy to do that. The `md` extension is kept as original. The `services.md` is a template similar to `_include/publications.md` now. Customization of services can be done in the `_data/services.yml`.

Thanks again for your contributions! And I am sorry for the misunderstanding. When I was saying "an improved version," I didn't mean a new pull request but a new repository under your GitHub account. I could add the link of your new repository to the README.md in my current repository, saying, "This is an improved version from @Xiao-Chenguang." I hope this could work. 

As I mentioned in my previous comments, I prefer not to make any edits to the current `services.md` and `publications.md`. You could do this in your new repository. Thanks for your understanding!

**Comment by Xiao-Chenguang** [comment]
I got you. That works great for me too.

**Comment by yaoyao-liu** [comment]
A note has been added to the README.md of my project to provide the link to your updated version. Please feel free to let me know if you have any further questions.

Thanks,
Yaoyao

**Pull request closed without merging**
